spring.application.name=spring-boot:camunda8-job worker

server.port=8081

camunda.client.mode=simple
camunda.client.zeebe.enabled=true
camunda.client.zeebe.grpc-address=http://localhost:26500
camunda.client.zeebe.rest-address= http://localhost:8080
